// IMProtocol.proto
// 自定义 IM 协议定义（使用 Protocol Buffers）
// 编译命令：protoc --go_out=. --go_opt=paths=source_relative im_protocol.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: im_protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 命令类型
type CommandType int32

const (
	CommandType_CMD_UNKNOWN CommandType = 0
	// 连接相关（1-99）
	CommandType_CMD_CONNECT_REQ    CommandType = 1 // 连接请求
	CommandType_CMD_CONNECT_RSP    CommandType = 2 // 连接响应
	CommandType_CMD_DISCONNECT_REQ CommandType = 3 // 断开请求
	CommandType_CMD_DISCONNECT_RSP CommandType = 4 // 断开响应
	CommandType_CMD_HEARTBEAT_REQ  CommandType = 5 // 心跳请求
	CommandType_CMD_HEARTBEAT_RSP  CommandType = 6 // 心跳响应
	// 认证相关（100-199）
	CommandType_CMD_AUTH_REQ   CommandType = 100 // 认证请求
	CommandType_CMD_AUTH_RSP   CommandType = 101 // 认证响应
	CommandType_CMD_REAUTH_REQ CommandType = 102 // 重新认证请求
	CommandType_CMD_REAUTH_RSP CommandType = 103 // 重新认证响应
	CommandType_CMD_KICK_OUT   CommandType = 104 // 踢出通知
	// 消息相关（200-299）
	CommandType_CMD_SEND_MSG_REQ    CommandType = 200 // 发送消息请求
	CommandType_CMD_SEND_MSG_RSP    CommandType = 201 // 发送消息响应
	CommandType_CMD_PUSH_MSG        CommandType = 202 // 推送消息（服务器 → 客户端）
	CommandType_CMD_MSG_ACK         CommandType = 203 // 消息 ACK
	CommandType_CMD_BATCH_MSG       CommandType = 204 // 批量消息
	CommandType_CMD_REVOKE_MSG_REQ  CommandType = 205 // 撤回消息请求
	CommandType_CMD_REVOKE_MSG_RSP  CommandType = 206 // 撤回消息响应
	CommandType_CMD_REVOKE_MSG_PUSH CommandType = 207 // 撤回消息推送
	// 同步相关（300-399）
	CommandType_CMD_BATCH_SYNC_REQ CommandType = 300 // 批量同步请求（一次性同步所有会话）
	CommandType_CMD_BATCH_SYNC_RSP CommandType = 301 // 批量同步响应
	CommandType_CMD_SYNC_FINISHED  CommandType = 302 // 同步完成通知
	CommandType_CMD_SYNC_RANGE_REQ CommandType = 303 // 范围同步请求（补拉丢失消息）
	CommandType_CMD_SYNC_RANGE_RSP CommandType = 304 // 范围同步响应
	// 在线状态（400-499）
	CommandType_CMD_ONLINE_STATUS_REQ  CommandType = 400 // 查询在线状态请求
	CommandType_CMD_ONLINE_STATUS_RSP  CommandType = 401 // 在线状态响应
	CommandType_CMD_STATUS_CHANGE_PUSH CommandType = 402 // 状态变化推送
	// 已读回执（500-599）
	CommandType_CMD_READ_RECEIPT_REQ  CommandType = 500 // 已读回执请求
	CommandType_CMD_READ_RECEIPT_RSP  CommandType = 501 // 已读回执响应
	CommandType_CMD_READ_RECEIPT_PUSH CommandType = 502 // 已读回执推送
	// 输入状态（600-699）
	CommandType_CMD_TYPING_STATUS_REQ  CommandType = 600 // 输入状态请求
	CommandType_CMD_TYPING_STATUS_PUSH CommandType = 601 // 输入状态推送
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0:   "CMD_UNKNOWN",
		1:   "CMD_CONNECT_REQ",
		2:   "CMD_CONNECT_RSP",
		3:   "CMD_DISCONNECT_REQ",
		4:   "CMD_DISCONNECT_RSP",
		5:   "CMD_HEARTBEAT_REQ",
		6:   "CMD_HEARTBEAT_RSP",
		100: "CMD_AUTH_REQ",
		101: "CMD_AUTH_RSP",
		102: "CMD_REAUTH_REQ",
		103: "CMD_REAUTH_RSP",
		104: "CMD_KICK_OUT",
		200: "CMD_SEND_MSG_REQ",
		201: "CMD_SEND_MSG_RSP",
		202: "CMD_PUSH_MSG",
		203: "CMD_MSG_ACK",
		204: "CMD_BATCH_MSG",
		205: "CMD_REVOKE_MSG_REQ",
		206: "CMD_REVOKE_MSG_RSP",
		207: "CMD_REVOKE_MSG_PUSH",
		300: "CMD_BATCH_SYNC_REQ",
		301: "CMD_BATCH_SYNC_RSP",
		302: "CMD_SYNC_FINISHED",
		303: "CMD_SYNC_RANGE_REQ",
		304: "CMD_SYNC_RANGE_RSP",
		400: "CMD_ONLINE_STATUS_REQ",
		401: "CMD_ONLINE_STATUS_RSP",
		402: "CMD_STATUS_CHANGE_PUSH",
		500: "CMD_READ_RECEIPT_REQ",
		501: "CMD_READ_RECEIPT_RSP",
		502: "CMD_READ_RECEIPT_PUSH",
		600: "CMD_TYPING_STATUS_REQ",
		601: "CMD_TYPING_STATUS_PUSH",
	}
	CommandType_value = map[string]int32{
		"CMD_UNKNOWN":            0,
		"CMD_CONNECT_REQ":        1,
		"CMD_CONNECT_RSP":        2,
		"CMD_DISCONNECT_REQ":     3,
		"CMD_DISCONNECT_RSP":     4,
		"CMD_HEARTBEAT_REQ":      5,
		"CMD_HEARTBEAT_RSP":      6,
		"CMD_AUTH_REQ":           100,
		"CMD_AUTH_RSP":           101,
		"CMD_REAUTH_REQ":         102,
		"CMD_REAUTH_RSP":         103,
		"CMD_KICK_OUT":           104,
		"CMD_SEND_MSG_REQ":       200,
		"CMD_SEND_MSG_RSP":       201,
		"CMD_PUSH_MSG":           202,
		"CMD_MSG_ACK":            203,
		"CMD_BATCH_MSG":          204,
		"CMD_REVOKE_MSG_REQ":     205,
		"CMD_REVOKE_MSG_RSP":     206,
		"CMD_REVOKE_MSG_PUSH":    207,
		"CMD_BATCH_SYNC_REQ":     300,
		"CMD_BATCH_SYNC_RSP":     301,
		"CMD_SYNC_FINISHED":      302,
		"CMD_SYNC_RANGE_REQ":     303,
		"CMD_SYNC_RANGE_RSP":     304,
		"CMD_ONLINE_STATUS_REQ":  400,
		"CMD_ONLINE_STATUS_RSP":  401,
		"CMD_STATUS_CHANGE_PUSH": 402,
		"CMD_READ_RECEIPT_REQ":   500,
		"CMD_READ_RECEIPT_RSP":   501,
		"CMD_READ_RECEIPT_PUSH":  502,
		"CMD_TYPING_STATUS_REQ":  600,
		"CMD_TYPING_STATUS_PUSH": 601,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_im_protocol_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_im_protocol_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{0}
}

// 错误码
type ErrorCode int32

const (
	ErrorCode_ERR_SUCCESS                ErrorCode = 0   // 成功
	ErrorCode_ERR_UNKNOWN                ErrorCode = 1   // 未知错误
	ErrorCode_ERR_INVALID_PARAM          ErrorCode = 2   // 参数错误
	ErrorCode_ERR_AUTH_FAILED            ErrorCode = 100 // 认证失败
	ErrorCode_ERR_TOKEN_EXPIRED          ErrorCode = 101 // Token 过期
	ErrorCode_ERR_PERMISSION_DENIED      ErrorCode = 102 // 权限不足
	ErrorCode_ERR_USER_NOT_EXIST         ErrorCode = 103 // 用户不存在
	ErrorCode_ERR_MESSAGE_TOO_LARGE      ErrorCode = 200 // 消息过大
	ErrorCode_ERR_SEND_TOO_FAST          ErrorCode = 201 // 发送过快
	ErrorCode_ERR_CONVERSATION_NOT_EXIST ErrorCode = 202 // 会话不存在
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "ERR_SUCCESS",
		1:   "ERR_UNKNOWN",
		2:   "ERR_INVALID_PARAM",
		100: "ERR_AUTH_FAILED",
		101: "ERR_TOKEN_EXPIRED",
		102: "ERR_PERMISSION_DENIED",
		103: "ERR_USER_NOT_EXIST",
		200: "ERR_MESSAGE_TOO_LARGE",
		201: "ERR_SEND_TOO_FAST",
		202: "ERR_CONVERSATION_NOT_EXIST",
	}
	ErrorCode_value = map[string]int32{
		"ERR_SUCCESS":                0,
		"ERR_UNKNOWN":                1,
		"ERR_INVALID_PARAM":          2,
		"ERR_AUTH_FAILED":            100,
		"ERR_TOKEN_EXPIRED":          101,
		"ERR_PERMISSION_DENIED":      102,
		"ERR_USER_NOT_EXIST":         103,
		"ERR_MESSAGE_TOO_LARGE":      200,
		"ERR_SEND_TOO_FAST":          201,
		"ERR_CONVERSATION_NOT_EXIST": 202,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_im_protocol_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_im_protocol_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{1}
}

// 连接请求
type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                                                      // 客户端 ID
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`                                                                      // 平台（iOS/Android/Web）
	AppVersion    string                 `protobuf:"bytes,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`                                                // App 版本
	SdkVersion    string                 `protobuf:"bytes,4,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`                                                // SDK 版本
	DeviceInfo    string                 `protobuf:"bytes,5,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`                                                // 设备信息
	Extra         map[string]string      `protobuf:"bytes,10,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_im_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ConnectRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ConnectRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *ConnectRequest) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *ConnectRequest) GetDeviceInfo() string {
	if x != nil {
		return x.DeviceInfo
	}
	return ""
}

func (x *ConnectRequest) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// 连接响应
type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=im.protocol.ErrorCode" json:"error_code,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	ServerTime    int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // 服务器时间（毫秒）
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`     // 会话 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_im_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERR_SUCCESS
}

func (x *ConnectResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ConnectResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *ConnectResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    int64                  `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"` // 客户端时间（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_im_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

// 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // 服务器时间（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_im_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// 认证请求
type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_im_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *AuthRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

// 认证响应
type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=im.protocol.ErrorCode" json:"error_code,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	MaxSeq        int64                  `protobuf:"varint,3,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"` // 当前最大序列号（用于增量同步）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_im_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *AuthResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERR_SUCCESS
}

func (x *AuthResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *AuthResponse) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

// 踢出通知
type KickOutNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        int32                  `protobuf:"varint,1,opt,name=reason,proto3" json:"reason,omitempty"` // 踢出原因（1: 其他设备登录，2: 账号异常等）
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickOutNotification) Reset() {
	*x = KickOutNotification{}
	mi := &file_im_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickOutNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickOutNotification) ProtoMessage() {}

func (x *KickOutNotification) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickOutNotification.ProtoReflect.Descriptor instead.
func (*KickOutNotification) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *KickOutNotification) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *KickOutNotification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 通用消息信息（各场景复用）
type MessageInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerMsgId      string                 `protobuf:"bytes,1,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`                // ✅ 服务器消息 ID（发送时为空，由服务端生成）
	ClientMsgId      string                 `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`                // 客户端消息 ID
	ConversationId   string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`         // 会话 ID
	SenderId         string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                           // 发送者 ID
	ReceiverId       string                 `protobuf:"bytes,5,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`                     // 接收者 ID（单聊）
	GroupId          string                 `protobuf:"bytes,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                              // 群组 ID（群聊）
	MessageType      int32                  `protobuf:"varint,7,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`                 // 消息类型
	Content          []byte                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`                                             // 消息内容（JSON 字节）
	SendTime         int64                  `protobuf:"varint,9,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`                          // 发送时间
	ServerTime       int64                  `protobuf:"varint,10,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`                   // 服务器时间
	Seq              int64                  `protobuf:"varint,11,opt,name=seq,proto3" json:"seq,omitempty"`                                                   // 消息序列号（发送时为0，由服务端生成）
	Status           int32                  `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`                                             // 消息状态（同步时使用）
	IsRead           bool                   `protobuf:"varint,13,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`                               // 是否已读（同步时使用）
	CreateTime       int64                  `protobuf:"varint,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                   // 创建时间（客户端创建消息的时间）
	Extra            string                 `protobuf:"bytes,15,opt,name=extra,proto3" json:"extra,omitempty"`                                                // 扩展字段（JSON 字符串）
	ReadBy           []string               `protobuf:"bytes,16,rep,name=read_by,json=readBy,proto3" json:"read_by,omitempty"`                                // 已读者 ID 列表（群聊）
	ReadTime         int64                  `protobuf:"varint,17,opt,name=read_time,json=readTime,proto3" json:"read_time,omitempty"`                         // 读取时间（单聊）
	IsDeleted        bool                   `protobuf:"varint,18,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`                      // 是否已删除
	IsRevoked        bool                   `protobuf:"varint,19,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`                      // 是否已撤回
	RevokedBy        string                 `protobuf:"bytes,20,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"`                       // 撤回者 ID
	RevokedTime      int64                  `protobuf:"varint,21,opt,name=revoked_time,json=revokedTime,proto3" json:"revoked_time,omitempty"`                // 撤回时间
	AttachedInfo     string                 `protobuf:"bytes,22,opt,name=attached_info,json=attachedInfo,proto3" json:"attached_info,omitempty"`              // 附加信息
	ConversationType int32                  `protobuf:"varint,23,opt,name=conversation_type,json=conversationType,proto3" json:"conversation_type,omitempty"` // 会话类型（1=单聊，2=群聊，3=聊天室，4=系统消息）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MessageInfo) Reset() {
	*x = MessageInfo{}
	mi := &file_im_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInfo) ProtoMessage() {}

func (x *MessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInfo.ProtoReflect.Descriptor instead.
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *MessageInfo) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *MessageInfo) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MessageInfo) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageInfo) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessageInfo) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *MessageInfo) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *MessageInfo) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *MessageInfo) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MessageInfo) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *MessageInfo) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *MessageInfo) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MessageInfo) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *MessageInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *MessageInfo) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *MessageInfo) GetReadBy() []string {
	if x != nil {
		return x.ReadBy
	}
	return nil
}

func (x *MessageInfo) GetReadTime() int64 {
	if x != nil {
		return x.ReadTime
	}
	return 0
}

func (x *MessageInfo) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *MessageInfo) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

func (x *MessageInfo) GetRevokedBy() string {
	if x != nil {
		return x.RevokedBy
	}
	return ""
}

func (x *MessageInfo) GetRevokedTime() int64 {
	if x != nil {
		return x.RevokedTime
	}
	return 0
}

func (x *MessageInfo) GetAttachedInfo() string {
	if x != nil {
		return x.AttachedInfo
	}
	return ""
}

func (x *MessageInfo) GetConversationType() int32 {
	if x != nil {
		return x.ConversationType
	}
	return 0
}

// 发送消息请求
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *MessageInfo           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // ✅ 复用通用消息结构
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_im_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetMessage() *MessageInfo {
	if x != nil {
		return x.Message
	}
	return nil
}

// 发送消息响应
type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=im.protocol.ErrorCode" json:"error_code,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	ServerMsgId   string                 `protobuf:"bytes,3,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"` // ✅ 服务器消息 ID
	ClientMsgId   string                 `protobuf:"bytes,4,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // 客户端消息 ID（用于匹配本地消息）
	Seq           int64                  `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`                                     // 消息序列号
	ServerTime    int64                  `protobuf:"varint,6,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`     // 服务器时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_im_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *SendMessageResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERR_SUCCESS
}

func (x *SendMessageResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *SendMessageResponse) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *SendMessageResponse) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *SendMessageResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SendMessageResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// 推送消息
type PushMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *MessageInfo           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // ✅ 复用通用消息结构
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessage) Reset() {
	*x = PushMessage{}
	mi := &file_im_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessage) ProtoMessage() {}

func (x *PushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessage.ProtoReflect.Descriptor instead.
func (*PushMessage) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *PushMessage) GetMessage() *MessageInfo {
	if x != nil {
		return x.Message
	}
	return nil
}

// 消息 ACK
type MessageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerMsgId   string                 `protobuf:"bytes,1,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"` // ✅ 服务器消息 ID
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAck) Reset() {
	*x = MessageAck{}
	mi := &file_im_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAck) ProtoMessage() {}

func (x *MessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAck.ProtoReflect.Descriptor instead.
func (*MessageAck) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *MessageAck) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *MessageAck) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// 批量消息
type BatchMessages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*PushMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMessages) Reset() {
	*x = BatchMessages{}
	mi := &file_im_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMessages) ProtoMessage() {}

func (x *BatchMessages) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMessages.ProtoReflect.Descriptor instead.
func (*BatchMessages) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *BatchMessages) GetMessages() []*PushMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 撤回消息请求
type RevokeMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerMsgId    string                 `protobuf:"bytes,1,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"` // ✅ 服务器消息 ID
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RevokeMessageRequest) Reset() {
	*x = RevokeMessageRequest{}
	mi := &file_im_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMessageRequest) ProtoMessage() {}

func (x *RevokeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMessageRequest.ProtoReflect.Descriptor instead.
func (*RevokeMessageRequest) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *RevokeMessageRequest) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *RevokeMessageRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// 撤回消息响应
type RevokeMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=im.protocol.ErrorCode" json:"error_code,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeMessageResponse) Reset() {
	*x = RevokeMessageResponse{}
	mi := &file_im_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMessageResponse) ProtoMessage() {}

func (x *RevokeMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMessageResponse.ProtoReflect.Descriptor instead.
func (*RevokeMessageResponse) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *RevokeMessageResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERR_SUCCESS
}

func (x *RevokeMessageResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 撤回消息推送
type RevokeMessagePush struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerMsgId    string                 `protobuf:"bytes,1,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"` // ✅ 服务器消息 ID
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	RevokedBy      string                 `protobuf:"bytes,3,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"`
	RevokedTime    int64                  `protobuf:"varint,4,opt,name=revoked_time,json=revokedTime,proto3" json:"revoked_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RevokeMessagePush) Reset() {
	*x = RevokeMessagePush{}
	mi := &file_im_protocol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeMessagePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMessagePush) ProtoMessage() {}

func (x *RevokeMessagePush) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMessagePush.ProtoReflect.Descriptor instead.
func (*RevokeMessagePush) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *RevokeMessagePush) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *RevokeMessagePush) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *RevokeMessagePush) GetRevokedBy() string {
	if x != nil {
		return x.RevokedBy
	}
	return ""
}

func (x *RevokeMessagePush) GetRevokedTime() int64 {
	if x != nil {
		return x.RevokedTime
	}
	return 0
}

// 会话同步状态（客户端本地状态）
type ConversationSyncState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 会话ID
	LastSeq        int64                  `protobuf:"varint,2,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`                     // 本地最大 seq
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationSyncState) Reset() {
	*x = ConversationSyncState{}
	mi := &file_im_protocol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationSyncState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationSyncState) ProtoMessage() {}

func (x *ConversationSyncState) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationSyncState.ProtoReflect.Descriptor instead.
func (*ConversationSyncState) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{16}
}

func (x *ConversationSyncState) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationSyncState) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

// 批量同步请求（一次性同步所有会话）
type BatchSyncRequest struct {
	state                   protoimpl.MessageState   `protogen:"open.v1"`
	ConversationStates      []*ConversationSyncState `protobuf:"bytes,1,rep,name=conversation_states,json=conversationStates,proto3" json:"conversation_states,omitempty"`                     // 客户端的会话同步状态（可为空，表示首次全量同步）
	MaxCountPerConversation int32                    `protobuf:"varint,2,opt,name=max_count_per_conversation,json=maxCountPerConversation,proto3" json:"max_count_per_conversation,omitempty"` // 每个会话最多拉取的消息数（默认100，最大500）
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *BatchSyncRequest) Reset() {
	*x = BatchSyncRequest{}
	mi := &file_im_protocol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSyncRequest) ProtoMessage() {}

func (x *BatchSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSyncRequest.ProtoReflect.Descriptor instead.
func (*BatchSyncRequest) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{17}
}

func (x *BatchSyncRequest) GetConversationStates() []*ConversationSyncState {
	if x != nil {
		return x.ConversationStates
	}
	return nil
}

func (x *BatchSyncRequest) GetMaxCountPerConversation() int32 {
	if x != nil {
		return x.MaxCountPerConversation
	}
	return 0
}

// 会话消息结果
type ConversationMessages struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 会话ID
	Messages       []*MessageInfo         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`                                   // 消息列表
	MaxSeq         int64                  `protobuf:"varint,3,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`                        // 服务端该会话的最大 seq
	SyncedSeq      int64                  `protobuf:"varint,4,opt,name=synced_seq,json=syncedSeq,proto3" json:"synced_seq,omitempty"`               // 本次同步到的 seq（可能小于 max_seq，因为有 max_count 限制）
	HasMore        bool                   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                     // 是否还有更多消息未同步
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationMessages) Reset() {
	*x = ConversationMessages{}
	mi := &file_im_protocol_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMessages) ProtoMessage() {}

func (x *ConversationMessages) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMessages.ProtoReflect.Descriptor instead.
func (*ConversationMessages) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{18}
}

func (x *ConversationMessages) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationMessages) GetMessages() []*MessageInfo {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ConversationMessages) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *ConversationMessages) GetSyncedSeq() int64 {
	if x != nil {
		return x.SyncedSeq
	}
	return 0
}

func (x *ConversationMessages) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// 批量同步响应
type BatchSyncResponse struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	ErrorCode            ErrorCode               `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=im.protocol.ErrorCode" json:"error_code,omitempty"`
	ErrorMsg             string                  `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	ConversationMessages []*ConversationMessages `protobuf:"bytes,3,rep,name=conversation_messages,json=conversationMessages,proto3" json:"conversation_messages,omitempty"` // 所有会话的消息
	ServerTime           int64                   `protobuf:"varint,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`                              // 服务器时间
	TotalMessageCount    int32                   `protobuf:"varint,5,opt,name=total_message_count,json=totalMessageCount,proto3" json:"total_message_count,omitempty"`       // 本次同步的总消息数
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BatchSyncResponse) Reset() {
	*x = BatchSyncResponse{}
	mi := &file_im_protocol_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSyncResponse) ProtoMessage() {}

func (x *BatchSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSyncResponse.ProtoReflect.Descriptor instead.
func (*BatchSyncResponse) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{19}
}

func (x *BatchSyncResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERR_SUCCESS
}

func (x *BatchSyncResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *BatchSyncResponse) GetConversationMessages() []*ConversationMessages {
	if x != nil {
		return x.ConversationMessages
	}
	return nil
}

func (x *BatchSyncResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *BatchSyncResponse) GetTotalMessageCount() int32 {
	if x != nil {
		return x.TotalMessageCount
	}
	return 0
}

// 范围同步请求
type SyncRangeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                // 请求唯一标识（由客户端生成，用于响应匹配）
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 会话ID（必填）
	StartSeq       int64                  `protobuf:"varint,3,opt,name=start_seq,json=startSeq,proto3" json:"start_seq,omitempty"`                  // 起始 seq（包含）
	EndSeq         int64                  `protobuf:"varint,4,opt,name=end_seq,json=endSeq,proto3" json:"end_seq,omitempty"`                        // 结束 seq（包含）
	Count          int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`                                        // 单次拉取数量限制（默认100，最大500）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncRangeRequest) Reset() {
	*x = SyncRangeRequest{}
	mi := &file_im_protocol_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRangeRequest) ProtoMessage() {}

func (x *SyncRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRangeRequest.ProtoReflect.Descriptor instead.
func (*SyncRangeRequest) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{20}
}

func (x *SyncRangeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncRangeRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SyncRangeRequest) GetStartSeq() int64 {
	if x != nil {
		return x.StartSeq
	}
	return 0
}

func (x *SyncRangeRequest) GetEndSeq() int64 {
	if x != nil {
		return x.EndSeq
	}
	return 0
}

func (x *SyncRangeRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 范围同步响应
type SyncRangeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode      ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=im.protocol.ErrorCode" json:"error_code,omitempty"`
	ErrorMsg       string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	RequestId      string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                // 对应请求的 request_id
	ConversationId string                 `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 会话ID
	Messages       []*MessageInfo         `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`                                   // 消息列表
	StartSeq       int64                  `protobuf:"varint,6,opt,name=start_seq,json=startSeq,proto3" json:"start_seq,omitempty"`                  // 实际返回的起始 seq
	EndSeq         int64                  `protobuf:"varint,7,opt,name=end_seq,json=endSeq,proto3" json:"end_seq,omitempty"`                        // 实际返回的结束 seq
	HasMore        bool                   `protobuf:"varint,8,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                     // 是否还有更多消息（如果请求范围过大，需要分批拉取）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncRangeResponse) Reset() {
	*x = SyncRangeResponse{}
	mi := &file_im_protocol_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRangeResponse) ProtoMessage() {}

func (x *SyncRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRangeResponse.ProtoReflect.Descriptor instead.
func (*SyncRangeResponse) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{21}
}

func (x *SyncRangeResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERR_SUCCESS
}

func (x *SyncRangeResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *SyncRangeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncRangeResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SyncRangeResponse) GetMessages() []*MessageInfo {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SyncRangeResponse) GetStartSeq() int64 {
	if x != nil {
		return x.StartSeq
	}
	return 0
}

func (x *SyncRangeResponse) GetEndSeq() int64 {
	if x != nil {
		return x.EndSeq
	}
	return 0
}

func (x *SyncRangeResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// 已读回执请求
type ReadReceiptRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerMsgIds   []string               `protobuf:"bytes,1,rep,name=server_msg_ids,json=serverMsgIds,proto3" json:"server_msg_ids,omitempty"` // ✅ 服务器消息 ID 列表
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadReceiptRequest) Reset() {
	*x = ReadReceiptRequest{}
	mi := &file_im_protocol_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReceiptRequest) ProtoMessage() {}

func (x *ReadReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReceiptRequest.ProtoReflect.Descriptor instead.
func (*ReadReceiptRequest) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{22}
}

func (x *ReadReceiptRequest) GetServerMsgIds() []string {
	if x != nil {
		return x.ServerMsgIds
	}
	return nil
}

func (x *ReadReceiptRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// 已读回执响应
type ReadReceiptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=im.protocol.ErrorCode" json:"error_code,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadReceiptResponse) Reset() {
	*x = ReadReceiptResponse{}
	mi := &file_im_protocol_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReceiptResponse) ProtoMessage() {}

func (x *ReadReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReceiptResponse.ProtoReflect.Descriptor instead.
func (*ReadReceiptResponse) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{23}
}

func (x *ReadReceiptResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERR_SUCCESS
}

func (x *ReadReceiptResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 已读回执推送
type ReadReceiptPush struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerMsgIds   []string               `protobuf:"bytes,1,rep,name=server_msg_ids,json=serverMsgIds,proto3" json:"server_msg_ids,omitempty"` // ✅ 服务器消息 ID 列表
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReadTime       int64                  `protobuf:"varint,4,opt,name=read_time,json=readTime,proto3" json:"read_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadReceiptPush) Reset() {
	*x = ReadReceiptPush{}
	mi := &file_im_protocol_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReceiptPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReceiptPush) ProtoMessage() {}

func (x *ReadReceiptPush) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReceiptPush.ProtoReflect.Descriptor instead.
func (*ReadReceiptPush) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{24}
}

func (x *ReadReceiptPush) GetServerMsgIds() []string {
	if x != nil {
		return x.ServerMsgIds
	}
	return nil
}

func (x *ReadReceiptPush) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ReadReceiptPush) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReadReceiptPush) GetReadTime() int64 {
	if x != nil {
		return x.ReadTime
	}
	return 0
}

// 输入状态请求
type TypingStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Status         int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 0: 停止输入，1: 正在输入
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TypingStatusRequest) Reset() {
	*x = TypingStatusRequest{}
	mi := &file_im_protocol_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingStatusRequest) ProtoMessage() {}

func (x *TypingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingStatusRequest.ProtoReflect.Descriptor instead.
func (*TypingStatusRequest) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{25}
}

func (x *TypingStatusRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *TypingStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 输入状态推送
type TypingStatusPush struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status         int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TypingStatusPush) Reset() {
	*x = TypingStatusPush{}
	mi := &file_im_protocol_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingStatusPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingStatusPush) ProtoMessage() {}

func (x *TypingStatusPush) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingStatusPush.ProtoReflect.Descriptor instead.
func (*TypingStatusPush) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{26}
}

func (x *TypingStatusPush) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *TypingStatusPush) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TypingStatusPush) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// ============================================
// WebSocket 专用消息封装
// ============================================
//
// WebSocket 传输使用此通用消息格式（不使用 IMPacket header）
// WebSocket 自带消息边界和校验，无需额外的 length 和 CRC
type WebSocketMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       CommandType            `protobuf:"varint,1,opt,name=command,proto3,enum=im.protocol.CommandType" json:"command,omitempty"` // 命令类型
	Sequence      uint32                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`                            // 序列号
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                                     // 消息体（具体消息的 Protobuf 序列化）
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // 时间戳（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketMessage) Reset() {
	*x = WebSocketMessage{}
	mi := &file_im_protocol_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketMessage) ProtoMessage() {}

func (x *WebSocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_im_protocol_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketMessage.ProtoReflect.Descriptor instead.
func (*WebSocketMessage) Descriptor() ([]byte, []int) {
	return file_im_protocol_proto_rawDescGZIP(), []int{27}
}

func (x *WebSocketMessage) GetCommand() CommandType {
	if x != nil {
		return x.Command
	}
	return CommandType_CMD_UNKNOWN
}

func (x *WebSocketMessage) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *WebSocketMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *WebSocketMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_im_protocol_proto protoreflect.FileDescriptor

const file_im_protocol_proto_rawDesc = "" +
	"\n" +
	"\x11im_protocol.proto\x12\vim.protocol\"\xa4\x02\n" +
	"\x0eConnectRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1f\n" +
	"\vapp_version\x18\x03 \x01(\tR\n" +
	"appVersion\x12\x1f\n" +
	"\vsdk_version\x18\x04 \x01(\tR\n" +
	"sdkVersion\x12\x1f\n" +
	"\vdevice_info\x18\x05 \x01(\tR\n" +
	"deviceInfo\x12<\n" +
	"\x05extra\x18\n" +
	" \x03(\v2&.im.protocol.ConnectRequest.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x01\n" +
	"\x0fConnectResponse\x125\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x16.im.protocol.ErrorCodeR\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"3\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\"4\n" +
	"\x11HeartbeatResponse\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\"X\n" +
	"\vAuthRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\"{\n" +
	"\fAuthResponse\x125\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x16.im.protocol.ErrorCodeR\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x17\n" +
	"\amax_seq\x18\x03 \x01(\x03R\x06maxSeq\"G\n" +
	"\x13KickOutNotification\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\x05R\x06reason\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd4\x05\n" +
	"\vMessageInfo\x12\"\n" +
	"\rserver_msg_id\x18\x01 \x01(\tR\vserverMsgId\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\tR\vclientMsgId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x05 \x01(\tR\n" +
	"receiverId\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\tR\agroupId\x12!\n" +
	"\fmessage_type\x18\a \x01(\x05R\vmessageType\x12\x18\n" +
	"\acontent\x18\b \x01(\fR\acontent\x12\x1b\n" +
	"\tsend_time\x18\t \x01(\x03R\bsendTime\x12\x1f\n" +
	"\vserver_time\x18\n" +
	" \x01(\x03R\n" +
	"serverTime\x12\x10\n" +
	"\x03seq\x18\v \x01(\x03R\x03seq\x12\x16\n" +
	"\x06status\x18\f \x01(\x05R\x06status\x12\x17\n" +
	"\ais_read\x18\r \x01(\bR\x06isRead\x12\x1f\n" +
	"\vcreate_time\x18\x0e \x01(\x03R\n" +
	"createTime\x12\x14\n" +
	"\x05extra\x18\x0f \x01(\tR\x05extra\x12\x17\n" +
	"\aread_by\x18\x10 \x03(\tR\x06readBy\x12\x1b\n" +
	"\tread_time\x18\x11 \x01(\x03R\breadTime\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x12 \x01(\bR\tisDeleted\x12\x1d\n" +
	"\n" +
	"is_revoked\x18\x13 \x01(\bR\tisRevoked\x12\x1d\n" +
	"\n" +
	"revoked_by\x18\x14 \x01(\tR\trevokedBy\x12!\n" +
	"\frevoked_time\x18\x15 \x01(\x03R\vrevokedTime\x12#\n" +
	"\rattached_info\x18\x16 \x01(\tR\fattachedInfo\x12+\n" +
	"\x11conversation_type\x18\x17 \x01(\x05R\x10conversationType\"H\n" +
	"\x12SendMessageRequest\x122\n" +
	"\amessage\x18\x01 \x01(\v2\x18.im.protocol.MessageInfoR\amessage\"\xe4\x01\n" +
	"\x13SendMessageResponse\x125\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x16.im.protocol.ErrorCodeR\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\"\n" +
	"\rserver_msg_id\x18\x03 \x01(\tR\vserverMsgId\x12\"\n" +
	"\rclient_msg_id\x18\x04 \x01(\tR\vclientMsgId\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x03R\x03seq\x12\x1f\n" +
	"\vserver_time\x18\x06 \x01(\x03R\n" +
	"serverTime\"A\n" +
	"\vPushMessage\x122\n" +
	"\amessage\x18\x01 \x01(\v2\x18.im.protocol.MessageInfoR\amessage\"B\n" +
	"\n" +
	"MessageAck\x12\"\n" +
	"\rserver_msg_id\x18\x01 \x01(\tR\vserverMsgId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\"E\n" +
	"\rBatchMessages\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.im.protocol.PushMessageR\bmessages\"c\n" +
	"\x14RevokeMessageRequest\x12\"\n" +
	"\rserver_msg_id\x18\x01 \x01(\tR\vserverMsgId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\"k\n" +
	"\x15RevokeMessageResponse\x125\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x16.im.protocol.ErrorCodeR\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"\xa2\x01\n" +
	"\x11RevokeMessagePush\x12\"\n" +
	"\rserver_msg_id\x18\x01 \x01(\tR\vserverMsgId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"revoked_by\x18\x03 \x01(\tR\trevokedBy\x12!\n" +
	"\frevoked_time\x18\x04 \x01(\x03R\vrevokedTime\"[\n" +
	"\x15ConversationSyncState\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x19\n" +
	"\blast_seq\x18\x02 \x01(\x03R\alastSeq\"\xa4\x01\n" +
	"\x10BatchSyncRequest\x12S\n" +
	"\x13conversation_states\x18\x01 \x03(\v2\".im.protocol.ConversationSyncStateR\x12conversationStates\x12;\n" +
	"\x1amax_count_per_conversation\x18\x02 \x01(\x05R\x17maxCountPerConversation\"\xc8\x01\n" +
	"\x14ConversationMessages\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x124\n" +
	"\bmessages\x18\x02 \x03(\v2\x18.im.protocol.MessageInfoR\bmessages\x12\x17\n" +
	"\amax_seq\x18\x03 \x01(\x03R\x06maxSeq\x12\x1d\n" +
	"\n" +
	"synced_seq\x18\x04 \x01(\x03R\tsyncedSeq\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\"\x90\x02\n" +
	"\x11BatchSyncResponse\x125\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x16.im.protocol.ErrorCodeR\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12V\n" +
	"\x15conversation_messages\x18\x03 \x03(\v2!.im.protocol.ConversationMessagesR\x14conversationMessages\x12\x1f\n" +
	"\vserver_time\x18\x04 \x01(\x03R\n" +
	"serverTime\x12.\n" +
	"\x13total_message_count\x18\x05 \x01(\x05R\x11totalMessageCount\"\xa6\x01\n" +
	"\x10SyncRangeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tstart_seq\x18\x03 \x01(\x03R\bstartSeq\x12\x17\n" +
	"\aend_seq\x18\x04 \x01(\x03R\x06endSeq\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\"\xb6\x02\n" +
	"\x11SyncRangeResponse\x125\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x16.im.protocol.ErrorCodeR\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12'\n" +
	"\x0fconversation_id\x18\x04 \x01(\tR\x0econversationId\x124\n" +
	"\bmessages\x18\x05 \x03(\v2\x18.im.protocol.MessageInfoR\bmessages\x12\x1b\n" +
	"\tstart_seq\x18\x06 \x01(\x03R\bstartSeq\x12\x17\n" +
	"\aend_seq\x18\a \x01(\x03R\x06endSeq\x12\x19\n" +
	"\bhas_more\x18\b \x01(\bR\ahasMore\"c\n" +
	"\x12ReadReceiptRequest\x12$\n" +
	"\x0eserver_msg_ids\x18\x01 \x03(\tR\fserverMsgIds\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\"i\n" +
	"\x13ReadReceiptResponse\x125\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x16.im.protocol.ErrorCodeR\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"\x96\x01\n" +
	"\x0fReadReceiptPush\x12$\n" +
	"\x0eserver_msg_ids\x18\x01 \x03(\tR\fserverMsgIds\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tread_time\x18\x04 \x01(\x03R\breadTime\"V\n" +
	"\x13TypingStatusRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"l\n" +
	"\x10TypingStatusPush\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\x94\x01\n" +
	"\x10WebSocketMessage\x122\n" +
	"\acommand\x18\x01 \x01(\x0e2\x18.im.protocol.CommandTypeR\acommand\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\rR\bsequence\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp*\x93\x06\n" +
	"\vCommandType\x12\x0f\n" +
	"\vCMD_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fCMD_CONNECT_REQ\x10\x01\x12\x13\n" +
	"\x0fCMD_CONNECT_RSP\x10\x02\x12\x16\n" +
	"\x12CMD_DISCONNECT_REQ\x10\x03\x12\x16\n" +
	"\x12CMD_DISCONNECT_RSP\x10\x04\x12\x15\n" +
	"\x11CMD_HEARTBEAT_REQ\x10\x05\x12\x15\n" +
	"\x11CMD_HEARTBEAT_RSP\x10\x06\x12\x10\n" +
	"\fCMD_AUTH_REQ\x10d\x12\x10\n" +
	"\fCMD_AUTH_RSP\x10e\x12\x12\n" +
	"\x0eCMD_REAUTH_REQ\x10f\x12\x12\n" +
	"\x0eCMD_REAUTH_RSP\x10g\x12\x10\n" +
	"\fCMD_KICK_OUT\x10h\x12\x15\n" +
	"\x10CMD_SEND_MSG_REQ\x10\xc8\x01\x12\x15\n" +
	"\x10CMD_SEND_MSG_RSP\x10\xc9\x01\x12\x11\n" +
	"\fCMD_PUSH_MSG\x10\xca\x01\x12\x10\n" +
	"\vCMD_MSG_ACK\x10\xcb\x01\x12\x12\n" +
	"\rCMD_BATCH_MSG\x10\xcc\x01\x12\x17\n" +
	"\x12CMD_REVOKE_MSG_REQ\x10\xcd\x01\x12\x17\n" +
	"\x12CMD_REVOKE_MSG_RSP\x10\xce\x01\x12\x18\n" +
	"\x13CMD_REVOKE_MSG_PUSH\x10\xcf\x01\x12\x17\n" +
	"\x12CMD_BATCH_SYNC_REQ\x10\xac\x02\x12\x17\n" +
	"\x12CMD_BATCH_SYNC_RSP\x10\xad\x02\x12\x16\n" +
	"\x11CMD_SYNC_FINISHED\x10\xae\x02\x12\x17\n" +
	"\x12CMD_SYNC_RANGE_REQ\x10\xaf\x02\x12\x17\n" +
	"\x12CMD_SYNC_RANGE_RSP\x10\xb0\x02\x12\x1a\n" +
	"\x15CMD_ONLINE_STATUS_REQ\x10\x90\x03\x12\x1a\n" +
	"\x15CMD_ONLINE_STATUS_RSP\x10\x91\x03\x12\x1b\n" +
	"\x16CMD_STATUS_CHANGE_PUSH\x10\x92\x03\x12\x19\n" +
	"\x14CMD_READ_RECEIPT_REQ\x10\xf4\x03\x12\x19\n" +
	"\x14CMD_READ_RECEIPT_RSP\x10\xf5\x03\x12\x1a\n" +
	"\x15CMD_READ_RECEIPT_PUSH\x10\xf6\x03\x12\x1a\n" +
	"\x15CMD_TYPING_STATUS_REQ\x10\xd8\x04\x12\x1b\n" +
	"\x16CMD_TYPING_STATUS_PUSH\x10\xd9\x04*\xf8\x01\n" +
	"\tErrorCode\x12\x0f\n" +
	"\vERR_SUCCESS\x10\x00\x12\x0f\n" +
	"\vERR_UNKNOWN\x10\x01\x12\x15\n" +
	"\x11ERR_INVALID_PARAM\x10\x02\x12\x13\n" +
	"\x0fERR_AUTH_FAILED\x10d\x12\x15\n" +
	"\x11ERR_TOKEN_EXPIRED\x10e\x12\x19\n" +
	"\x15ERR_PERMISSION_DENIED\x10f\x12\x16\n" +
	"\x12ERR_USER_NOT_EXIST\x10g\x12\x1a\n" +
	"\x15ERR_MESSAGE_TOO_LARGE\x10\xc8\x01\x12\x16\n" +
	"\x11ERR_SEND_TOO_FAST\x10\xc9\x01\x12\x1f\n" +
	"\x1aERR_CONVERSATION_NOT_EXIST\x10\xca\x01B.Z,github.com/arwen/im-server/internal/protocolb\x06proto3"

var (
	file_im_protocol_proto_rawDescOnce sync.Once
	file_im_protocol_proto_rawDescData []byte
)

func file_im_protocol_proto_rawDescGZIP() []byte {
	file_im_protocol_proto_rawDescOnce.Do(func() {
		file_im_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_protocol_proto_rawDesc), len(file_im_protocol_proto_rawDesc)))
	})
	return file_im_protocol_proto_rawDescData
}

var file_im_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_im_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_im_protocol_proto_goTypes = []any{
	(CommandType)(0),              // 0: im.protocol.CommandType
	(ErrorCode)(0),                // 1: im.protocol.ErrorCode
	(*ConnectRequest)(nil),        // 2: im.protocol.ConnectRequest
	(*ConnectResponse)(nil),       // 3: im.protocol.ConnectResponse
	(*HeartbeatRequest)(nil),      // 4: im.protocol.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 5: im.protocol.HeartbeatResponse
	(*AuthRequest)(nil),           // 6: im.protocol.AuthRequest
	(*AuthResponse)(nil),          // 7: im.protocol.AuthResponse
	(*KickOutNotification)(nil),   // 8: im.protocol.KickOutNotification
	(*MessageInfo)(nil),           // 9: im.protocol.MessageInfo
	(*SendMessageRequest)(nil),    // 10: im.protocol.SendMessageRequest
	(*SendMessageResponse)(nil),   // 11: im.protocol.SendMessageResponse
	(*PushMessage)(nil),           // 12: im.protocol.PushMessage
	(*MessageAck)(nil),            // 13: im.protocol.MessageAck
	(*BatchMessages)(nil),         // 14: im.protocol.BatchMessages
	(*RevokeMessageRequest)(nil),  // 15: im.protocol.RevokeMessageRequest
	(*RevokeMessageResponse)(nil), // 16: im.protocol.RevokeMessageResponse
	(*RevokeMessagePush)(nil),     // 17: im.protocol.RevokeMessagePush
	(*ConversationSyncState)(nil), // 18: im.protocol.ConversationSyncState
	(*BatchSyncRequest)(nil),      // 19: im.protocol.BatchSyncRequest
	(*ConversationMessages)(nil),  // 20: im.protocol.ConversationMessages
	(*BatchSyncResponse)(nil),     // 21: im.protocol.BatchSyncResponse
	(*SyncRangeRequest)(nil),      // 22: im.protocol.SyncRangeRequest
	(*SyncRangeResponse)(nil),     // 23: im.protocol.SyncRangeResponse
	(*ReadReceiptRequest)(nil),    // 24: im.protocol.ReadReceiptRequest
	(*ReadReceiptResponse)(nil),   // 25: im.protocol.ReadReceiptResponse
	(*ReadReceiptPush)(nil),       // 26: im.protocol.ReadReceiptPush
	(*TypingStatusRequest)(nil),   // 27: im.protocol.TypingStatusRequest
	(*TypingStatusPush)(nil),      // 28: im.protocol.TypingStatusPush
	(*WebSocketMessage)(nil),      // 29: im.protocol.WebSocketMessage
	nil,                           // 30: im.protocol.ConnectRequest.ExtraEntry
}
var file_im_protocol_proto_depIdxs = []int32{
	30, // 0: im.protocol.ConnectRequest.extra:type_name -> im.protocol.ConnectRequest.ExtraEntry
	1,  // 1: im.protocol.ConnectResponse.error_code:type_name -> im.protocol.ErrorCode
	1,  // 2: im.protocol.AuthResponse.error_code:type_name -> im.protocol.ErrorCode
	9,  // 3: im.protocol.SendMessageRequest.message:type_name -> im.protocol.MessageInfo
	1,  // 4: im.protocol.SendMessageResponse.error_code:type_name -> im.protocol.ErrorCode
	9,  // 5: im.protocol.PushMessage.message:type_name -> im.protocol.MessageInfo
	12, // 6: im.protocol.BatchMessages.messages:type_name -> im.protocol.PushMessage
	1,  // 7: im.protocol.RevokeMessageResponse.error_code:type_name -> im.protocol.ErrorCode
	18, // 8: im.protocol.BatchSyncRequest.conversation_states:type_name -> im.protocol.ConversationSyncState
	9,  // 9: im.protocol.ConversationMessages.messages:type_name -> im.protocol.MessageInfo
	1,  // 10: im.protocol.BatchSyncResponse.error_code:type_name -> im.protocol.ErrorCode
	20, // 11: im.protocol.BatchSyncResponse.conversation_messages:type_name -> im.protocol.ConversationMessages
	1,  // 12: im.protocol.SyncRangeResponse.error_code:type_name -> im.protocol.ErrorCode
	9,  // 13: im.protocol.SyncRangeResponse.messages:type_name -> im.protocol.MessageInfo
	1,  // 14: im.protocol.ReadReceiptResponse.error_code:type_name -> im.protocol.ErrorCode
	0,  // 15: im.protocol.WebSocketMessage.command:type_name -> im.protocol.CommandType
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_im_protocol_proto_init() }
func file_im_protocol_proto_init() {
	if File_im_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_protocol_proto_rawDesc), len(file_im_protocol_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_im_protocol_proto_goTypes,
		DependencyIndexes: file_im_protocol_proto_depIdxs,
		EnumInfos:         file_im_protocol_proto_enumTypes,
		MessageInfos:      file_im_protocol_proto_msgTypes,
	}.Build()
	File_im_protocol_proto = out.File
	file_im_protocol_proto_goTypes = nil
	file_im_protocol_proto_depIdxs = nil
}
